// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using SigortaYonetimAPI.Models;

#nullable disable

namespace SigortaYonetimAPI.Migrations
{
    [DbContext(typeof(SigortaYonetimDbContext))]
    partial class SigortaYonetimDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.7")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("RoleId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetRoleClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.Property<string>("LoginProvider")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ProviderKey")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ProviderDisplayName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("LoginProvider", "ProviderKey");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserLogins", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("RoleId")
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("UserId", "RoleId");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetUserRoles", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("LoginProvider")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Value")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("UserId", "LoginProvider", "Name");

                    b.ToTable("AspNetUserTokens", (string)null);
                });

            modelBuilder.Entity("SigortaYonetimAPI.Models.ApplicationRole", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Aciklama")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("AktifMi")
                        .HasColumnType("bit");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("NormalizedName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<DateTime>("OlusturmaTarihi")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedName")
                        .IsUnique()
                        .HasDatabaseName("RoleNameIndex")
                        .HasFilter("[NormalizedName] IS NOT NULL");

                    b.ToTable("AspNetRoles", (string)null);
                });

            modelBuilder.Entity("SigortaYonetimAPI.Models.ApplicationUser", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<int>("AccessFailedCount")
                        .HasColumnType("int");

                    b.Property<string>("Ad")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("AktifMi")
                        .HasColumnType("bit");

                    b.Property<int>("BasarisizGirisSayisi")
                        .HasColumnType("int");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Departman")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Email")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<bool>("EmailConfirmed")
                        .HasColumnType("bit");

                    b.Property<bool>("EmailDogrulandi")
                        .HasColumnType("bit");

                    b.Property<DateTime>("GuncellemeTarihi")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("HesapKilitlenmeTarihi")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("KayitTarihi")
                        .HasColumnType("datetime2");

                    b.Property<int?>("KullanicilarId")
                        .HasColumnType("int");

                    b.Property<bool>("LockoutEnabled")
                        .HasColumnType("bit");

                    b.Property<DateTimeOffset?>("LockoutEnd")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("NormalizedEmail")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("NormalizedUserName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("Notlar")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PasswordHash")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PhoneNumber")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("PhoneNumberConfirmed")
                        .HasColumnType("bit");

                    b.Property<string>("Pozisyon")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("SecurityStamp")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("SonAktiviteTarihi")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("SonGirisTarihi")
                        .HasColumnType("datetime2");

                    b.Property<string>("SonIpAdresi")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Soyad")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Telefon")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("TelefonDogrulandi")
                        .HasColumnType("bit");

                    b.Property<bool>("TwoFactorEnabled")
                        .HasColumnType("bit");

                    b.Property<string>("UserName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("YoneticiId")
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("KullanicilarId");

                    b.HasIndex("NormalizedEmail")
                        .HasDatabaseName("EmailIndex");

                    b.HasIndex("NormalizedUserName")
                        .IsUnique()
                        .HasDatabaseName("UserNameIndex")
                        .HasFilter("[NormalizedUserName] IS NOT NULL");

                    b.HasIndex("YoneticiId");

                    b.ToTable("AspNetUsers", (string)null);
                });

            modelBuilder.Entity("SigortaYonetimAPI.Models.BILDIRIMLER", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("id"));

                    b.Property<int>("alici_kullanici_id")
                        .HasColumnType("int");

                    b.Property<string>("baslik")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<int?>("bildirim_tipi_id")
                        .HasColumnType("int");

                    b.Property<int>("durum_id")
                        .HasColumnType("int");

                    b.Property<DateTime>("gonderim_tarihi")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime")
                        .HasDefaultValueSql("(getdate())");

                    b.Property<string>("hata_mesaji")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<string>("icerik")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<int?>("kullanici_id")
                        .HasColumnType("int");

                    b.Property<string>("mesaj")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("musteri_id")
                        .HasColumnType("int");

                    b.Property<bool?>("okundu_mi")
                        .HasColumnType("bit");

                    b.Property<bool?>("okundu_mu")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(false);

                    b.Property<DateTime?>("okunma_tarihi")
                        .HasColumnType("datetime");

                    b.Property<DateTime?>("olusturma_tarihi")
                        .HasColumnType("datetime2");

                    b.Property<int?>("oncelik_id")
                        .HasColumnType("int");

                    b.HasKey("id")
                        .HasName("PK__BILDIRIM__3213E83F5EDBC28A");

                    b.HasIndex("alici_kullanici_id");

                    b.HasIndex("bildirim_tipi_id");

                    b.HasIndex("durum_id");

                    b.HasIndex("oncelik_id");

                    b.ToTable("BILDIRIMLER", (string)null);
                });

            modelBuilder.Entity("SigortaYonetimAPI.Models.DOGRULAMA_KODLARI", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("id"));

                    b.Property<int>("amac_id")
                        .HasColumnType("int");

                    b.Property<int?>("deneme_sayisi")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasDefaultValue(0);

                    b.Property<string>("kod")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<int>("kullanici_id")
                        .HasColumnType("int");

                    b.Property<bool>("kullanildi_mi")
                        .HasColumnType("bit");

                    b.Property<DateTime>("olusturma_tarihi")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime")
                        .HasDefaultValueSql("(getdate())");

                    b.Property<DateTime>("son_kullanma_tarihi")
                        .HasColumnType("datetime");

                    b.Property<int>("tip_id")
                        .HasColumnType("int");

                    b.HasKey("id")
                        .HasName("PK__DOGRULAM__3213E83FC3C872D7");

                    b.HasIndex("amac_id");

                    b.HasIndex("kullanici_id");

                    b.HasIndex("tip_id");

                    b.ToTable("DOGRULAMA_KODLARI", (string)null);
                });

            modelBuilder.Entity("SigortaYonetimAPI.Models.DOKUMANLAR", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("id"));

                    b.Property<string>("aciklama")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<string>("dosya_adi")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<int?>("dosya_boyutu")
                        .HasColumnType("int");

                    b.Property<long?>("dosya_boyutu_long")
                        .HasColumnType("bigint");

                    b.Property<int?>("dosya_tipi_id")
                        .HasColumnType("int");

                    b.Property<string>("dosya_turu")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("dosya_yolu")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<int?>("gizlilik_seviyesi_id")
                        .HasColumnType("int");

                    b.Property<string>("hash_degeri")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<int?>("iliski_id")
                        .HasColumnType("int");

                    b.Property<int?>("iliski_tipi_id")
                        .HasColumnType("int");

                    b.Property<int?>("kategori_id")
                        .HasColumnType("int");

                    b.Property<string>("mime_type")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<int?>("musteri_id")
                        .HasColumnType("int");

                    b.Property<int?>("musteriid")
                        .HasColumnType("int");

                    b.Property<string>("orijinal_dosya_adi")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<int?>("police_id")
                        .HasColumnType("int");

                    b.Property<int?>("policeid")
                        .HasColumnType("int");

                    b.Property<bool?>("silinebilir_mi")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(true);

                    b.Property<DateTime?>("son_erisim_tarihi")
                        .HasColumnType("datetime");

                    b.Property<DateTime>("yukleme_tarihi")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("yuklenme_tarihi")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime")
                        .HasDefaultValueSql("(getdate())");

                    b.Property<int?>("yukleyen_kullanici_id")
                        .HasColumnType("int");

                    b.Property<bool?>("zorunlu_mu")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(false);

                    b.HasKey("id")
                        .HasName("PK__DOKUMANL__3213E83F60EA8DE3");

                    b.HasIndex("dosya_tipi_id");

                    b.HasIndex("gizlilik_seviyesi_id");

                    b.HasIndex("iliski_tipi_id");

                    b.HasIndex("kategori_id");

                    b.HasIndex("musteriid");

                    b.HasIndex("policeid");

                    b.HasIndex("yukleyen_kullanici_id");

                    b.ToTable("DOKUMANLAR", (string)null);
                });

            modelBuilder.Entity("SigortaYonetimAPI.Models.DURUM_TANIMLARI", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("id"));

                    b.Property<bool>("aktif_mi")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(true);

                    b.Property<string>("alan_adi")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("deger_aciklama")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<string>("deger_kodu")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("grup")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("olusturma_tarihi")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime")
                        .HasDefaultValueSql("(getdate())");

                    b.Property<int>("siralama")
                        .HasColumnType("int");

                    b.Property<string>("tablo_adi")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("tanim")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("ust_id")
                        .HasColumnType("int");

                    b.HasKey("id")
                        .HasName("PK__DURUM_TA__3213E83F7B05CF3F");

                    b.ToTable("DURUM_TANIMLARI", (string)null);
                });

            modelBuilder.Entity("SigortaYonetimAPI.Models.HASAR_DOSYALAR", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("id"));

                    b.Property<string>("aciklama")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("bildiren_kullanici_id")
                        .HasColumnType("int");

                    b.Property<DateTime>("bildirim_tarihi")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime")
                        .HasDefaultValueSql("(getdate())");

                    b.Property<string>("dosya_no")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("durum_id")
                        .HasColumnType("int");

                    b.Property<DateTime?>("ekspertiz_tarihi")
                        .HasColumnType("datetime");

                    b.Property<decimal?>("ekspertiz_tutari")
                        .HasColumnType("decimal(18, 2)");

                    b.Property<DateTime>("guncelleme_tarihi")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime")
                        .HasDefaultValueSql("(getdate())");

                    b.Property<string>("hasar_no")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)");

                    b.Property<DateTime?>("karar_tarihi")
                        .HasColumnType("datetime");

                    b.Property<int>("musteri_id")
                        .HasColumnType("int");

                    b.Property<string>("notlar")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<DateTime?>("odeme_tarihi")
                        .HasColumnType("datetime");

                    b.Property<decimal?>("odenen_tutar")
                        .HasColumnType("decimal(18, 2)");

                    b.Property<string>("olay_aciklamasi")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<string>("olay_saati")
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)");

                    b.Property<DateTime>("olay_tarihi")
                        .HasColumnType("datetime");

                    b.Property<int?>("olay_tipi_id")
                        .HasColumnType("int");

                    b.Property<string>("olay_yeri_detay")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<string>("olay_yeri_il")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("olay_yeri_ilce")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<DateTime>("olusturma_tarihi")
                        .HasColumnType("datetime2");

                    b.Property<decimal?>("onaylanan_tutar")
                        .HasColumnType("decimal(18, 2)");

                    b.Property<string>("onaylayan_kullanici")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<int>("police_id")
                        .HasColumnType("int");

                    b.Property<string>("polis_rapor_no")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<bool?>("polis_raporu_var_mi")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(false);

                    b.Property<string>("red_nedeni")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<int?>("sorumlu_eksper_id")
                        .HasColumnType("int");

                    b.Property<decimal?>("talep_edilen_tutar")
                        .HasColumnType("decimal(18, 2)");

                    b.Property<string>("tanik_bilgileri")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<decimal?>("toplam_tutar")
                        .HasColumnType("decimal(18, 2)");

                    b.HasKey("id")
                        .HasName("PK__HASAR_DO__3213E83F9FD228F4");

                    b.HasIndex("bildiren_kullanici_id");

                    b.HasIndex("durum_id");

                    b.HasIndex("musteri_id");

                    b.HasIndex("olay_tipi_id");

                    b.HasIndex("police_id");

                    b.HasIndex("sorumlu_eksper_id");

                    b.HasIndex(new[] { "hasar_no" }, "UQ__HASAR_DO__59C8A1EAB87CF833")
                        .IsUnique();

                    b.ToTable("HASAR_DOSYALAR", (string)null);
                });

            modelBuilder.Entity("SigortaYonetimAPI.Models.HASAR_TAKIP_NOTLARI", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("id"));

                    b.Property<int>("hasar_id")
                        .HasColumnType("int");

                    b.Property<int>("kullanici_id")
                        .HasColumnType("int");

                    b.Property<string>("not_metni")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<int?>("not_tipi_id")
                        .HasColumnType("int");

                    b.Property<DateTime>("olusturma_tarihi")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime")
                        .HasDefaultValueSql("(getdate())");

                    b.HasKey("id")
                        .HasName("PK__HASAR_TA__3213E83F95ED626A");

                    b.HasIndex("hasar_id");

                    b.HasIndex("kullanici_id");

                    b.HasIndex("not_tipi_id");

                    b.ToTable("HASAR_TAKIP_NOTLARI", (string)null);
                });

            modelBuilder.Entity("SigortaYonetimAPI.Models.KOMISYON_HESAPLARI", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("id"));

                    b.Property<int>("acente_kullanici_id")
                        .HasColumnType("int");

                    b.Property<string>("aciklama")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<decimal?>("brut_prim")
                        .HasColumnType("decimal(18, 2)");

                    b.Property<int>("durum_id")
                        .HasColumnType("int");

                    b.Property<DateTime>("hesaplama_tarihi")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime")
                        .HasDefaultValueSql("(getdate())");

                    b.Property<decimal?>("komisyon_orani")
                        .HasColumnType("decimal(5, 2)");

                    b.Property<decimal?>("komisyon_tutari")
                        .HasColumnType("decimal(18, 2)");

                    b.Property<decimal?>("net_komisyon")
                        .HasColumnType("decimal(18, 2)");

                    b.Property<DateTime?>("odeme_tarihi")
                        .HasColumnType("datetime");

                    b.Property<int>("police_id")
                        .HasColumnType("int");

                    b.Property<decimal?>("stopaj_tutari")
                        .HasColumnType("decimal(18, 2)");

                    b.HasKey("id")
                        .HasName("PK__KOMISYON__3213E83F1FB37110");

                    b.HasIndex("acente_kullanici_id");

                    b.HasIndex("durum_id");

                    b.HasIndex("police_id");

                    b.ToTable("KOMISYON_HESAPLARI", (string)null);
                });

            modelBuilder.Entity("SigortaYonetimAPI.Models.KULLANICILAR", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("id"));

                    b.Property<string>("ad")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<int?>("basarisiz_giris_sayisi")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasDefaultValue(0);

                    b.Property<int>("durum_id")
                        .HasColumnType("int");

                    b.Property<bool>("email_dogrulandi")
                        .HasColumnType("bit");

                    b.Property<string>("eposta")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<DateTime>("guncelleme_tarihi")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime")
                        .HasDefaultValueSql("(getdate())");

                    b.Property<DateTime?>("hesap_kilitlenme_tarihi")
                        .HasColumnType("datetime");

                    b.Property<DateTime>("kayit_tarihi")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime")
                        .HasDefaultValueSql("(getdate())");

                    b.Property<string>("sifre_hash")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<DateTime?>("son_giris_tarihi")
                        .HasColumnType("datetime");

                    b.Property<string>("soyad")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("telefon")
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<bool>("telefon_dogrulandi")
                        .HasColumnType("bit");

                    b.HasKey("id")
                        .HasName("PK__KULLANIC__3213E83F9E2CBCE3");

                    b.HasIndex("durum_id");

                    b.HasIndex(new[] { "eposta" }, "UQ__KULLANIC__2549FEE6C5DAC599")
                        .IsUnique();

                    b.ToTable("KULLANICILAR", (string)null);
                });

            modelBuilder.Entity("SigortaYonetimAPI.Models.MUSTERILER", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("id"));

                    b.Property<int?>("DURUM_TANIMLARIid")
                        .HasColumnType("int");

                    b.Property<string>("ad")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("adres_detay")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<string>("adres_il")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("adres_ilce")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("adres_mahalle")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<decimal?>("aylik_gelir")
                        .HasColumnType("decimal(18, 2)");

                    b.Property<bool?>("blacklist_mi")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(false);

                    b.Property<string>("blacklist_nedeni")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<int?>("cinsiyet_id")
                        .HasColumnType("int");

                    b.Property<DateOnly?>("dogum_tarihi")
                        .HasColumnType("date");

                    b.Property<int?>("egitim_durumu_id")
                        .HasColumnType("int");

                    b.Property<string>("eposta")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<DateTime>("guncelleme_tarihi")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime")
                        .HasDefaultValueSql("(getdate())");

                    b.Property<string>("kaydeden_kullanici")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<DateTime>("kayit_tarihi")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime")
                        .HasDefaultValueSql("(getdate())");

                    b.Property<int?>("kullanici_id")
                        .HasColumnType("int");

                    b.Property<int?>("medeni_durum_id")
                        .HasColumnType("int");

                    b.Property<string>("meslek")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("musteri_no")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)");

                    b.Property<string>("not_bilgileri")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<string>("posta_kodu")
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)");

                    b.Property<string>("sirket_adi")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("soyad")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("tc_kimlik_no")
                        .HasMaxLength(11)
                        .HasColumnType("nvarchar(11)");

                    b.Property<string>("telefon")
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<string>("vergi_no")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("id")
                        .HasName("PK__MUSTERIL__3213E83FA69A30A2");

                    b.HasIndex("DURUM_TANIMLARIid");

                    b.HasIndex("cinsiyet_id");

                    b.HasIndex("egitim_durumu_id");

                    b.HasIndex("kullanici_id");

                    b.HasIndex("medeni_durum_id");

                    b.HasIndex(new[] { "musteri_no" }, "UQ__MUSTERIL__966D2E8C6CAD6128")
                        .IsUnique();

                    b.ToTable("MUSTERILER", (string)null);
                });

            modelBuilder.Entity("SigortaYonetimAPI.Models.ODEMELER", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("id"));

                    b.Property<string>("aciklama")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<string>("banka_adi")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("banka_referans_no")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<int>("durum_id")
                        .HasColumnType("int");

                    b.Property<string>("fis_no")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("kart_son_4_hane")
                        .HasMaxLength(4)
                        .HasColumnType("nvarchar(4)");

                    b.Property<decimal?>("komisyon_tutari")
                        .HasColumnType("decimal(18, 2)");

                    b.Property<string>("makbuz_no")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<DateTime?>("muhasebe_kayit_tarihi")
                        .HasColumnType("datetime");

                    b.Property<bool?>("muhasebede_kaydedildi_mi")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(false);

                    b.Property<int>("musteri_id")
                        .HasColumnType("int");

                    b.Property<string>("odeme_no")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("odeme_tarihi")
                        .HasColumnType("datetime");

                    b.Property<int?>("odeme_tipi_id")
                        .HasColumnType("int");

                    b.Property<string>("odeme_turu")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("odeme_yontemi_id")
                        .HasColumnType("int");

                    b.Property<DateTime>("olusturma_tarihi")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime")
                        .HasDefaultValueSql("(getdate())");

                    b.Property<int?>("police_id")
                        .HasColumnType("int");

                    b.Property<string>("pos_referans_no")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<DateTime?>("tahsil_tarihi")
                        .HasColumnType("datetime");

                    b.Property<int?>("tahsilat_yapan_kullanici_id")
                        .HasColumnType("int");

                    b.Property<int?>("taksit_id")
                        .HasColumnType("int");

                    b.Property<int?>("taksit_sayisi")
                        .HasColumnType("int");

                    b.Property<decimal?>("taksit_tutari")
                        .HasColumnType("decimal(18, 2)");

                    b.Property<decimal>("tutar")
                        .HasColumnType("decimal(18, 2)");

                    b.Property<DateTime?>("vade_tarihi")
                        .HasColumnType("datetime2");

                    b.HasKey("id")
                        .HasName("PK__ODEMELER__3213E83F191C5CE6");

                    b.HasIndex("durum_id");

                    b.HasIndex("musteri_id");

                    b.HasIndex("odeme_tipi_id");

                    b.HasIndex("odeme_yontemi_id");

                    b.HasIndex("police_id");

                    b.HasIndex("tahsilat_yapan_kullanici_id");

                    b.HasIndex("taksit_id");

                    b.ToTable("ODEMELER", (string)null);
                });

            modelBuilder.Entity("SigortaYonetimAPI.Models.POLICE_TEKLIFLERI", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("id"));

                    b.Property<decimal?>("brut_prim")
                        .HasColumnType("decimal(18, 2)");

                    b.Property<int>("durum_id")
                        .HasColumnType("int");

                    b.Property<DateTime?>("gecerlilik_tarihi")
                        .HasColumnType("datetime");

                    b.Property<DateTime>("guncelleme_tarihi")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime")
                        .HasDefaultValueSql("(getdate())");

                    b.Property<decimal?>("komisyon_tutari")
                        .HasColumnType("decimal(18, 2)");

                    b.Property<int>("musteri_id")
                        .HasColumnType("int");

                    b.Property<decimal?>("net_prim")
                        .HasColumnType("decimal(18, 2)");

                    b.Property<string>("notlar")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<int>("olusturan_kullanici_id")
                        .HasColumnType("int");

                    b.Property<DateTime>("olusturma_tarihi")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime")
                        .HasDefaultValueSql("(getdate())");

                    b.Property<DateTime?>("onay_tarihi")
                        .HasColumnType("datetime");

                    b.Property<string>("onaylayan_kullanici")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<int>("police_turu_id")
                        .HasColumnType("int");

                    b.Property<string>("red_nedeni")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<string>("risk_bilgileri")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<int>("sigorta_sirketi_id")
                        .HasColumnType("int");

                    b.Property<int?>("taksit_sayisi")
                        .HasColumnType("int");

                    b.Property<string>("teklif_no")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)");

                    b.Property<DateTime>("teklif_tarihi")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime")
                        .HasDefaultValueSql("(getdate())");

                    b.Property<string>("teminat_bilgileri")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<decimal?>("toplam_tutar")
                        .HasColumnType("decimal(18, 2)");

                    b.Property<decimal?>("vergi_tutari")
                        .HasColumnType("decimal(18, 2)");

                    b.HasKey("id")
                        .HasName("PK__POLICE_T__3213E83F46F858E7");

                    b.HasIndex("durum_id");

                    b.HasIndex("musteri_id");

                    b.HasIndex("olusturan_kullanici_id");

                    b.HasIndex("police_turu_id");

                    b.HasIndex("sigorta_sirketi_id");

                    b.HasIndex(new[] { "teklif_no" }, "UQ__POLICE_T__A90A1AD96B121A3B")
                        .IsUnique();

                    b.ToTable("POLICE_TEKLIFLERI", (string)null);
                });

            modelBuilder.Entity("SigortaYonetimAPI.Models.POLICE_TURLERI", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("id"));

                    b.Property<string>("aciklama")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<bool>("aktif_mi")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(true);

                    b.Property<int>("alt_kategori_id")
                        .HasColumnType("int");

                    b.Property<int>("kategori_id")
                        .HasColumnType("int");

                    b.Property<int?>("max_sure_gun")
                        .HasColumnType("int");

                    b.Property<decimal?>("max_tutar")
                        .HasColumnType("decimal(18, 2)");

                    b.Property<int?>("min_sure_gun")
                        .HasColumnType("int");

                    b.Property<decimal?>("min_tutar")
                        .HasColumnType("decimal(18, 2)");

                    b.Property<DateTime>("olusturma_tarihi")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime")
                        .HasDefaultValueSql("(getdate())");

                    b.Property<string>("risk_faktorleri")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<string>("urun_adi")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("urun_kodu")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<bool?>("zorunlu_mi")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(false);

                    b.HasKey("id")
                        .HasName("PK__POLICE_T__3213E83F4A0077E7");

                    b.HasIndex("alt_kategori_id");

                    b.HasIndex("kategori_id");

                    b.HasIndex(new[] { "urun_kodu" }, "UQ__POLICE_T__1359E5D30D80A072")
                        .IsUnique();

                    b.ToTable("POLICE_TURLERI", (string)null);
                });

            modelBuilder.Entity("SigortaYonetimAPI.Models.POLISELER", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("id"));

                    b.Property<DateTime>("baslangic_tarihi")
                        .HasColumnType("datetime");

                    b.Property<DateTime>("bitis_tarihi")
                        .HasColumnType("datetime");

                    b.Property<decimal?>("brut_prim")
                        .HasColumnType("decimal(18, 2)");

                    b.Property<int>("durum_id")
                        .HasColumnType("int");

                    b.Property<DateTime>("guncelleme_tarihi")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime")
                        .HasDefaultValueSql("(getdate())");

                    b.Property<string>("iptal_nedeni")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<DateTime?>("iptal_tarihi")
                        .HasColumnType("datetime");

                    b.Property<decimal?>("komisyon_tutari")
                        .HasColumnType("decimal(18, 2)");

                    b.Property<int>("musteri_id")
                        .HasColumnType("int");

                    b.Property<decimal?>("net_prim")
                        .HasColumnType("decimal(18, 2)");

                    b.Property<string>("notlar")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<string>("ozel_sartlar")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<string>("police_no")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)");

                    b.Property<int>("police_turu_id")
                        .HasColumnType("int");

                    b.Property<string>("risk_bilgileri")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<int>("sigorta_sirketi_id")
                        .HasColumnType("int");

                    b.Property<int?>("taksit_sayisi")
                        .HasColumnType("int");

                    b.Property<int>("tanzim_eden_kullanici_id")
                        .HasColumnType("int");

                    b.Property<DateTime>("tanzim_tarihi")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime")
                        .HasDefaultValueSql("(getdate())");

                    b.Property<int?>("teklif_id")
                        .HasColumnType("int");

                    b.Property<string>("teminat_bilgileri")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<decimal?>("toplam_tutar")
                        .HasColumnType("decimal(18, 2)");

                    b.Property<decimal?>("vergi_tutari")
                        .HasColumnType("decimal(18, 2)");

                    b.Property<DateTime?>("yenileme_hatirlatma_tarihi")
                        .HasColumnType("datetime");

                    b.HasKey("id")
                        .HasName("PK__POLISELE__3213E83F0ECB3EC8");

                    b.HasIndex("durum_id");

                    b.HasIndex("musteri_id");

                    b.HasIndex("police_turu_id");

                    b.HasIndex("sigorta_sirketi_id");

                    b.HasIndex("tanzim_eden_kullanici_id");

                    b.HasIndex("teklif_id");

                    b.HasIndex(new[] { "police_no" }, "UQ__POLISELE__68FFBEFB8254C983")
                        .IsUnique();

                    b.ToTable("POLISELER", (string)null);
                });

            modelBuilder.Entity("SigortaYonetimAPI.Models.RAPOR_SABLONLARI", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("id"));

                    b.Property<bool>("aktif_mi")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(true);

                    b.Property<int?>("cikti_formati_id")
                        .HasColumnType("int");

                    b.Property<int?>("olusturan_kullanici_id")
                        .HasColumnType("int");

                    b.Property<DateTime>("olusturma_tarihi")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime")
                        .HasDefaultValueSql("(getdate())");

                    b.Property<bool?>("otomatik_mi")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(false);

                    b.Property<string>("parametreler")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<string>("rapor_adi")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<int?>("rapor_tipi_id")
                        .HasColumnType("int");

                    b.Property<string>("sql_sorgusu")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("zamanlama_id")
                        .HasColumnType("int");

                    b.HasKey("id")
                        .HasName("PK__RAPOR_SA__3213E83FC1E43606");

                    b.HasIndex("cikti_formati_id");

                    b.HasIndex("olusturan_kullanici_id");

                    b.HasIndex("rapor_tipi_id");

                    b.HasIndex("zamanlama_id");

                    b.ToTable("RAPOR_SABLONLARI", (string)null);
                });

            modelBuilder.Entity("SigortaYonetimAPI.Models.SIFRE_SIFIRLAMA", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("id"));

                    b.Property<string>("ip_adresi")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<int>("kullanici_id")
                        .HasColumnType("int");

                    b.Property<bool>("kullanildi_mi")
                        .HasColumnType("bit");

                    b.Property<DateTime>("olusturma_tarihi")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime")
                        .HasDefaultValueSql("(getdate())");

                    b.Property<DateTime>("son_kullanma_tarihi")
                        .HasColumnType("datetime");

                    b.Property<string>("token")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.HasKey("id")
                        .HasName("PK__SIFRE_SI__3213E83FB8C30544");

                    b.HasIndex("kullanici_id");

                    b.ToTable("SIFRE_SIFIRLAMA", (string)null);
                });

            modelBuilder.Entity("SigortaYonetimAPI.Models.SIGORTA_SIRKETLERI", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("id"));

                    b.Property<string>("adres")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<bool>("aktif_mi")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(true);

                    b.Property<string>("eposta")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<decimal?>("komisyon_orani")
                        .HasColumnType("decimal(5, 2)");

                    b.Property<string>("sirket_adi")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("sirket_kodu")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<DateTime?>("sozlesme_baslangic")
                        .HasColumnType("datetime");

                    b.Property<DateTime?>("sozlesme_bitis")
                        .HasColumnType("datetime");

                    b.Property<string>("telefon")
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<string>("vergi_no")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("id")
                        .HasName("PK__SIGORTA___3213E83FD9ED5039");

                    b.HasIndex(new[] { "sirket_kodu" }, "UQ__SIGORTA___C10CA9E75367FF1C")
                        .IsUnique();

                    b.ToTable("SIGORTA_SIRKETLERI", (string)null);
                });

            modelBuilder.Entity("SigortaYonetimAPI.Models.SISTEM_LOGLARI", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("id"));

                    b.Property<string>("aciklama")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<string>("eski_deger")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ip_adresi")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<DateTime>("islem_tarihi")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime")
                        .HasDefaultValueSql("(getdate())");

                    b.Property<int?>("islem_tipi_id")
                        .HasColumnType("int");

                    b.Property<int?>("kayit_id")
                        .HasColumnType("int");

                    b.Property<int?>("kullanici_id")
                        .HasColumnType("int");

                    b.Property<string>("tablo_adi")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("tarayici_bilgisi")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<string>("yeni_deger")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("id")
                        .HasName("PK__SISTEM_L__3213E83FED74E8C7");

                    b.HasIndex("islem_tipi_id");

                    b.HasIndex("kullanici_id");

                    b.ToTable("SISTEM_LOGLARI", (string)null);
                });

            modelBuilder.Entity("SigortaYonetimAPI.Models.TAKSITLER", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("id"));

                    b.Property<decimal?>("ana_para")
                        .HasColumnType("decimal(18, 2)");

                    b.Property<int>("durum_id")
                        .HasColumnType("int");

                    b.Property<decimal?>("gecikme_faizi")
                        .HasColumnType("decimal(18, 2)");

                    b.Property<int?>("gecikme_gun_sayisi")
                        .HasColumnType("int");

                    b.Property<int?>("hatirlatma_durumu_id")
                        .HasColumnType("int");

                    b.Property<int?>("odeme_id")
                        .HasColumnType("int");

                    b.Property<DateTime?>("odeme_tarihi")
                        .HasColumnType("datetime");

                    b.Property<int?>("odemeid")
                        .HasColumnType("int");

                    b.Property<DateTime>("olusturma_tarihi")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime")
                        .HasDefaultValueSql("(getdate())");

                    b.Property<int>("police_id")
                        .HasColumnType("int");

                    b.Property<DateTime?>("son_hatirlatma_tarihi")
                        .HasColumnType("datetime");

                    b.Property<int>("taksit_no")
                        .HasColumnType("int");

                    b.Property<decimal>("toplam_tutar")
                        .HasColumnType("decimal(18, 2)");

                    b.Property<DateTime>("vade_tarihi")
                        .HasColumnType("datetime");

                    b.Property<decimal?>("vergi_tutari")
                        .HasColumnType("decimal(18, 2)");

                    b.HasKey("id")
                        .HasName("PK__TAKSITLE__3213E83FE1900BE8");

                    b.HasIndex("durum_id");

                    b.HasIndex("hatirlatma_durumu_id");

                    b.HasIndex("odemeid");

                    b.HasIndex("police_id");

                    b.ToTable("TAKSITLER", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.HasOne("SigortaYonetimAPI.Models.ApplicationRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.HasOne("SigortaYonetimAPI.Models.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.HasOne("SigortaYonetimAPI.Models.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.HasOne("SigortaYonetimAPI.Models.ApplicationRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("SigortaYonetimAPI.Models.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.HasOne("SigortaYonetimAPI.Models.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("SigortaYonetimAPI.Models.ApplicationUser", b =>
                {
                    b.HasOne("SigortaYonetimAPI.Models.KULLANICILAR", "Kullanici")
                        .WithMany()
                        .HasForeignKey("KullanicilarId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("SigortaYonetimAPI.Models.ApplicationUser", "Yonetici")
                        .WithMany("AstKullanicilar")
                        .HasForeignKey("YoneticiId")
                        .OnDelete(DeleteBehavior.NoAction);

                    b.Navigation("Kullanici");

                    b.Navigation("Yonetici");
                });

            modelBuilder.Entity("SigortaYonetimAPI.Models.BILDIRIMLER", b =>
                {
                    b.HasOne("SigortaYonetimAPI.Models.KULLANICILAR", "alici_kullanici")
                        .WithMany("BILDIRIMLERs")
                        .HasForeignKey("alici_kullanici_id")
                        .IsRequired()
                        .HasConstraintName("FK__BILDIRIML__alici__489AC854");

                    b.HasOne("SigortaYonetimAPI.Models.DURUM_TANIMLARI", "bildirim_tipi")
                        .WithMany("BILDIRIMLERbildirim_tipis")
                        .HasForeignKey("bildirim_tipi_id")
                        .HasConstraintName("FK__BILDIRIML__bildi__498EEC8D");

                    b.HasOne("SigortaYonetimAPI.Models.DURUM_TANIMLARI", "durum")
                        .WithMany("BILDIRIMLERdurums")
                        .HasForeignKey("durum_id")
                        .IsRequired()
                        .HasConstraintName("FK__BILDIRIML__durum__4B7734FF");

                    b.HasOne("SigortaYonetimAPI.Models.DURUM_TANIMLARI", "oncelik")
                        .WithMany("BILDIRIMLERonceliks")
                        .HasForeignKey("oncelik_id")
                        .HasConstraintName("FK__BILDIRIML__oncel__4A8310C6");

                    b.Navigation("alici_kullanici");

                    b.Navigation("bildirim_tipi");

                    b.Navigation("durum");

                    b.Navigation("oncelik");
                });

            modelBuilder.Entity("SigortaYonetimAPI.Models.DOGRULAMA_KODLARI", b =>
                {
                    b.HasOne("SigortaYonetimAPI.Models.DURUM_TANIMLARI", "amac")
                        .WithMany("DOGRULAMA_KODLARIamacs")
                        .HasForeignKey("amac_id")
                        .IsRequired()
                        .HasConstraintName("FK__DOGRULAMA__amac___4D94879B");

                    b.HasOne("SigortaYonetimAPI.Models.KULLANICILAR", "kullanici")
                        .WithMany("DOGRULAMA_KODLARIs")
                        .HasForeignKey("kullanici_id")
                        .IsRequired()
                        .HasConstraintName("FK__DOGRULAMA__kulla__4BAC3F29");

                    b.HasOne("SigortaYonetimAPI.Models.DURUM_TANIMLARI", "tip")
                        .WithMany("DOGRULAMA_KODLARItips")
                        .HasForeignKey("tip_id")
                        .IsRequired()
                        .HasConstraintName("FK__DOGRULAMA__tip_i__4CA06362");

                    b.Navigation("amac");

                    b.Navigation("kullanici");

                    b.Navigation("tip");
                });

            modelBuilder.Entity("SigortaYonetimAPI.Models.DOKUMANLAR", b =>
                {
                    b.HasOne("SigortaYonetimAPI.Models.DURUM_TANIMLARI", "dosya_tipi")
                        .WithMany("DOKUMANLARdosya_tipis")
                        .HasForeignKey("dosya_tipi_id")
                        .HasConstraintName("FK__DOKUMANLA__dosya__3C34F16F");

                    b.HasOne("SigortaYonetimAPI.Models.DURUM_TANIMLARI", "gizlilik_seviyesi")
                        .WithMany("DOKUMANLARgizlilik_seviyesis")
                        .HasForeignKey("gizlilik_seviyesi_id")
                        .HasConstraintName("FK__DOKUMANLA__gizli__3E1D39E1");

                    b.HasOne("SigortaYonetimAPI.Models.DURUM_TANIMLARI", "iliski_tipi")
                        .WithMany("DOKUMANLARiliski_tipis")
                        .HasForeignKey("iliski_tipi_id")
                        .HasConstraintName("FK__DOKUMANLA__ilisk__3B40CD36");

                    b.HasOne("SigortaYonetimAPI.Models.DURUM_TANIMLARI", "kategori")
                        .WithMany("DOKUMANLARkategoris")
                        .HasForeignKey("kategori_id")
                        .HasConstraintName("FK__DOKUMANLA__kateg__3D2915A8");

                    b.HasOne("SigortaYonetimAPI.Models.MUSTERILER", "musteri")
                        .WithMany()
                        .HasForeignKey("musteriid");

                    b.HasOne("SigortaYonetimAPI.Models.POLISELER", "police")
                        .WithMany()
                        .HasForeignKey("policeid");

                    b.HasOne("SigortaYonetimAPI.Models.KULLANICILAR", "yukleyen_kullanici")
                        .WithMany("DOKUMANLARs")
                        .HasForeignKey("yukleyen_kullanici_id")
                        .HasConstraintName("FK__DOKUMANLA__yukle__3F115E1A");

                    b.Navigation("dosya_tipi");

                    b.Navigation("gizlilik_seviyesi");

                    b.Navigation("iliski_tipi");

                    b.Navigation("kategori");

                    b.Navigation("musteri");

                    b.Navigation("police");

                    b.Navigation("yukleyen_kullanici");
                });

            modelBuilder.Entity("SigortaYonetimAPI.Models.HASAR_DOSYALAR", b =>
                {
                    b.HasOne("SigortaYonetimAPI.Models.KULLANICILAR", "bildiren_kullanici")
                        .WithMany("HASAR_DOSYALARbildiren_kullanicis")
                        .HasForeignKey("bildiren_kullanici_id")
                        .IsRequired()
                        .HasConstraintName("FK__HASAR_DOS__bildi__17036CC0");

                    b.HasOne("SigortaYonetimAPI.Models.DURUM_TANIMLARI", "durum")
                        .WithMany("HASAR_DOSYALARdurums")
                        .HasForeignKey("durum_id")
                        .IsRequired()
                        .HasConstraintName("FK__HASAR_DOS__durum__18EBB532");

                    b.HasOne("SigortaYonetimAPI.Models.MUSTERILER", "musteri")
                        .WithMany("HASAR_DOSYALARs")
                        .HasForeignKey("musteri_id")
                        .IsRequired()
                        .HasConstraintName("FK__HASAR_DOS__muste__160F4887");

                    b.HasOne("SigortaYonetimAPI.Models.DURUM_TANIMLARI", "olay_tipi")
                        .WithMany("HASAR_DOSYALARolay_tipis")
                        .HasForeignKey("olay_tipi_id")
                        .HasConstraintName("FK__HASAR_DOS__olay___17F790F9");

                    b.HasOne("SigortaYonetimAPI.Models.POLISELER", "police")
                        .WithMany("HASAR_DOSYALARs")
                        .HasForeignKey("police_id")
                        .IsRequired()
                        .HasConstraintName("FK__HASAR_DOS__polic__151B244E");

                    b.HasOne("SigortaYonetimAPI.Models.KULLANICILAR", "sorumlu_eksper")
                        .WithMany("HASAR_DOSYALARsorumlu_ekspers")
                        .HasForeignKey("sorumlu_eksper_id")
                        .HasConstraintName("FK__HASAR_DOS__sorum__19DFD96B");

                    b.Navigation("bildiren_kullanici");

                    b.Navigation("durum");

                    b.Navigation("musteri");

                    b.Navigation("olay_tipi");

                    b.Navigation("police");

                    b.Navigation("sorumlu_eksper");
                });

            modelBuilder.Entity("SigortaYonetimAPI.Models.HASAR_TAKIP_NOTLARI", b =>
                {
                    b.HasOne("SigortaYonetimAPI.Models.HASAR_DOSYALAR", "hasar")
                        .WithMany("HASAR_TAKIP_NOTLARIs")
                        .HasForeignKey("hasar_id")
                        .IsRequired()
                        .HasConstraintName("FK__HASAR_TAK__hasar__1DB06A4F");

                    b.HasOne("SigortaYonetimAPI.Models.KULLANICILAR", "kullanici")
                        .WithMany("HASAR_TAKIP_NOTLARIs")
                        .HasForeignKey("kullanici_id")
                        .IsRequired()
                        .HasConstraintName("FK__HASAR_TAK__kulla__1EA48E88");

                    b.HasOne("SigortaYonetimAPI.Models.DURUM_TANIMLARI", "not_tipi")
                        .WithMany("HASAR_TAKIP_NOTLARIs")
                        .HasForeignKey("not_tipi_id")
                        .HasConstraintName("FK__HASAR_TAK__not_t__1F98B2C1");

                    b.Navigation("hasar");

                    b.Navigation("kullanici");

                    b.Navigation("not_tipi");
                });

            modelBuilder.Entity("SigortaYonetimAPI.Models.KOMISYON_HESAPLARI", b =>
                {
                    b.HasOne("SigortaYonetimAPI.Models.KULLANICILAR", "acente_kullanici")
                        .WithMany("KOMISYON_HESAPLARIs")
                        .HasForeignKey("acente_kullanici_id")
                        .IsRequired()
                        .HasConstraintName("FK__KOMISYON___acent__3493CFA7");

                    b.HasOne("SigortaYonetimAPI.Models.DURUM_TANIMLARI", "durum")
                        .WithMany("KOMISYON_HESAPLARIs")
                        .HasForeignKey("durum_id")
                        .IsRequired()
                        .HasConstraintName("FK__KOMISYON___durum__3587F3E0");

                    b.HasOne("SigortaYonetimAPI.Models.POLISELER", "police")
                        .WithMany("KOMISYON_HESAPLARIs")
                        .HasForeignKey("police_id")
                        .IsRequired()
                        .HasConstraintName("FK__KOMISYON___polic__339FAB6E");

                    b.Navigation("acente_kullanici");

                    b.Navigation("durum");

                    b.Navigation("police");
                });

            modelBuilder.Entity("SigortaYonetimAPI.Models.KULLANICILAR", b =>
                {
                    b.HasOne("SigortaYonetimAPI.Models.DURUM_TANIMLARI", "durum")
                        .WithMany("KULLANICILARs")
                        .HasForeignKey("durum_id")
                        .IsRequired()
                        .HasConstraintName("FK__KULLANICI__durum__412EB0B6");

                    b.Navigation("durum");
                });

            modelBuilder.Entity("SigortaYonetimAPI.Models.MUSTERILER", b =>
                {
                    b.HasOne("SigortaYonetimAPI.Models.DURUM_TANIMLARI", null)
                        .WithMany("MUSTERILERtips")
                        .HasForeignKey("DURUM_TANIMLARIid");

                    b.HasOne("SigortaYonetimAPI.Models.DURUM_TANIMLARI", "cinsiyet")
                        .WithMany("MUSTERILERcinsiyets")
                        .HasForeignKey("cinsiyet_id")
                        .HasConstraintName("FK__MUSTERILE__cinsi__6383C8BA");

                    b.HasOne("SigortaYonetimAPI.Models.DURUM_TANIMLARI", "egitim_durumu")
                        .WithMany("MUSTERILERegitim_durumus")
                        .HasForeignKey("egitim_durumu_id")
                        .HasConstraintName("FK__MUSTERILE__egiti__656C112C");

                    b.HasOne("SigortaYonetimAPI.Models.KULLANICILAR", "kullanici")
                        .WithMany("MUSTERILERs")
                        .HasForeignKey("kullanici_id")
                        .HasConstraintName("FK__MUSTERILE__kulla__619B8048");

                    b.HasOne("SigortaYonetimAPI.Models.DURUM_TANIMLARI", "medeni_durum")
                        .WithMany("MUSTERILERmedeni_durums")
                        .HasForeignKey("medeni_durum_id")
                        .HasConstraintName("FK__MUSTERILE__meden__6477ECF3");

                    b.Navigation("cinsiyet");

                    b.Navigation("egitim_durumu");

                    b.Navigation("kullanici");

                    b.Navigation("medeni_durum");
                });

            modelBuilder.Entity("SigortaYonetimAPI.Models.ODEMELER", b =>
                {
                    b.HasOne("SigortaYonetimAPI.Models.DURUM_TANIMLARI", "durum")
                        .WithMany("ODEMELERdurums")
                        .HasForeignKey("durum_id")
                        .IsRequired()
                        .HasConstraintName("FK__ODEMELER__durum___2FCF1A8A");

                    b.HasOne("SigortaYonetimAPI.Models.MUSTERILER", "musteri")
                        .WithMany("ODEMELERs")
                        .HasForeignKey("musteri_id")
                        .IsRequired()
                        .HasConstraintName("FK__ODEMELER__muster__2BFE89A6");

                    b.HasOne("SigortaYonetimAPI.Models.DURUM_TANIMLARI", "odeme_tipi")
                        .WithMany("ODEMELERodeme_tipis")
                        .HasForeignKey("odeme_tipi_id")
                        .HasConstraintName("FK__ODEMELER__odeme___2DE6D218");

                    b.HasOne("SigortaYonetimAPI.Models.DURUM_TANIMLARI", "odeme_yontemi")
                        .WithMany("ODEMELERodeme_yontemis")
                        .HasForeignKey("odeme_yontemi_id")
                        .HasConstraintName("FK__ODEMELER__odeme___2EDAF651");

                    b.HasOne("SigortaYonetimAPI.Models.POLISELER", "police")
                        .WithMany("ODEMELERs")
                        .HasForeignKey("police_id")
                        .HasConstraintName("FK__ODEMELER__police__2B0A656D");

                    b.HasOne("SigortaYonetimAPI.Models.KULLANICILAR", "tahsilat_yapan_kullanici")
                        .WithMany("ODEMELERs")
                        .HasForeignKey("tahsilat_yapan_kullanici_id")
                        .HasConstraintName("FK__ODEMELER__tahsil__2CF2ADDF");

                    b.HasOne("SigortaYonetimAPI.Models.TAKSITLER", "taksit")
                        .WithMany("ODEMELERs")
                        .HasForeignKey("taksit_id")
                        .HasConstraintName("FK__ODEMELER__taksit__2A164134");

                    b.Navigation("durum");

                    b.Navigation("musteri");

                    b.Navigation("odeme_tipi");

                    b.Navigation("odeme_yontemi");

                    b.Navigation("police");

                    b.Navigation("tahsilat_yapan_kullanici");

                    b.Navigation("taksit");
                });

            modelBuilder.Entity("SigortaYonetimAPI.Models.POLICE_TEKLIFLERI", b =>
                {
                    b.HasOne("SigortaYonetimAPI.Models.DURUM_TANIMLARI", "durum")
                        .WithMany("POLICE_TEKLIFLERIs")
                        .HasForeignKey("durum_id")
                        .IsRequired()
                        .HasConstraintName("FK__POLICE_TE__durum__03F0984C");

                    b.HasOne("SigortaYonetimAPI.Models.MUSTERILER", "musteri")
                        .WithMany("POLICE_TEKLIFLERIs")
                        .HasForeignKey("musteri_id")
                        .IsRequired()
                        .HasConstraintName("FK__POLICE_TE__muste__00200768");

                    b.HasOne("SigortaYonetimAPI.Models.KULLANICILAR", "olusturan_kullanici")
                        .WithMany("POLICE_TEKLIFLERIs")
                        .HasForeignKey("olusturan_kullanici_id")
                        .IsRequired()
                        .HasConstraintName("FK__POLICE_TE__olust__02FC7413");

                    b.HasOne("SigortaYonetimAPI.Models.POLICE_TURLERI", "police_turu")
                        .WithMany("POLICE_TEKLIFLERIs")
                        .HasForeignKey("police_turu_id")
                        .IsRequired()
                        .HasConstraintName("FK__POLICE_TE__polic__01142BA1");

                    b.HasOne("SigortaYonetimAPI.Models.SIGORTA_SIRKETLERI", "sigorta_sirketi")
                        .WithMany("POLICE_TEKLIFLERIs")
                        .HasForeignKey("sigorta_sirketi_id")
                        .IsRequired()
                        .HasConstraintName("FK__POLICE_TE__sigor__02084FDA");

                    b.Navigation("durum");

                    b.Navigation("musteri");

                    b.Navigation("olusturan_kullanici");

                    b.Navigation("police_turu");

                    b.Navigation("sigorta_sirketi");
                });

            modelBuilder.Entity("SigortaYonetimAPI.Models.POLICE_TURLERI", b =>
                {
                    b.HasOne("SigortaYonetimAPI.Models.DURUM_TANIMLARI", "alt_kategori")
                        .WithMany("POLICE_TURLERIalt_kategoris")
                        .HasForeignKey("alt_kategori_id")
                        .IsRequired()
                        .HasConstraintName("FK__POLICE_TU__alt_k__797309D9");

                    b.HasOne("SigortaYonetimAPI.Models.DURUM_TANIMLARI", "kategori")
                        .WithMany("POLICE_TURLERIkategoris")
                        .HasForeignKey("kategori_id")
                        .IsRequired()
                        .HasConstraintName("FK__POLICE_TU__kateg__787EE5A0");

                    b.Navigation("alt_kategori");

                    b.Navigation("kategori");
                });

            modelBuilder.Entity("SigortaYonetimAPI.Models.POLISELER", b =>
                {
                    b.HasOne("SigortaYonetimAPI.Models.DURUM_TANIMLARI", "durum")
                        .WithMany("POLISELERs")
                        .HasForeignKey("durum_id")
                        .IsRequired()
                        .HasConstraintName("FK__POLISELER__durum__0E6E26BF");

                    b.HasOne("SigortaYonetimAPI.Models.MUSTERILER", "musteri")
                        .WithMany("POLISELERs")
                        .HasForeignKey("musteri_id")
                        .IsRequired()
                        .HasConstraintName("FK__POLISELER__muste__0A9D95DB");

                    b.HasOne("SigortaYonetimAPI.Models.POLICE_TURLERI", "police_turu")
                        .WithMany("POLISELERs")
                        .HasForeignKey("police_turu_id")
                        .IsRequired()
                        .HasConstraintName("FK__POLISELER__polic__0B91BA14");

                    b.HasOne("SigortaYonetimAPI.Models.SIGORTA_SIRKETLERI", "sigorta_sirketi")
                        .WithMany("POLISELERs")
                        .HasForeignKey("sigorta_sirketi_id")
                        .IsRequired()
                        .HasConstraintName("FK__POLISELER__sigor__0C85DE4D");

                    b.HasOne("SigortaYonetimAPI.Models.KULLANICILAR", "tanzim_eden_kullanici")
                        .WithMany("POLISELERs")
                        .HasForeignKey("tanzim_eden_kullanici_id")
                        .IsRequired()
                        .HasConstraintName("FK__POLISELER__tanzi__0D7A0286");

                    b.HasOne("SigortaYonetimAPI.Models.POLICE_TEKLIFLERI", "teklif")
                        .WithMany("POLISELERs")
                        .HasForeignKey("teklif_id")
                        .HasConstraintName("FK__POLISELER__tekli__09A971A2");

                    b.Navigation("durum");

                    b.Navigation("musteri");

                    b.Navigation("police_turu");

                    b.Navigation("sigorta_sirketi");

                    b.Navigation("tanzim_eden_kullanici");

                    b.Navigation("teklif");
                });

            modelBuilder.Entity("SigortaYonetimAPI.Models.RAPOR_SABLONLARI", b =>
                {
                    b.HasOne("SigortaYonetimAPI.Models.DURUM_TANIMLARI", "cikti_formati")
                        .WithMany("RAPOR_SABLONLARIcikti_formatis")
                        .HasForeignKey("cikti_formati_id")
                        .HasConstraintName("FK__RAPOR_SAB__cikti__5224328E");

                    b.HasOne("SigortaYonetimAPI.Models.KULLANICILAR", "olusturan_kullanici")
                        .WithMany("RAPOR_SABLONLARIs")
                        .HasForeignKey("olusturan_kullanici_id")
                        .HasConstraintName("FK__RAPOR_SAB__olust__540C7B00");

                    b.HasOne("SigortaYonetimAPI.Models.DURUM_TANIMLARI", "rapor_tipi")
                        .WithMany("RAPOR_SABLONLARIrapor_tipis")
                        .HasForeignKey("rapor_tipi_id")
                        .HasConstraintName("FK__RAPOR_SAB__rapor__51300E55");

                    b.HasOne("SigortaYonetimAPI.Models.DURUM_TANIMLARI", "zamanlama")
                        .WithMany("RAPOR_SABLONLARIzamanlamas")
                        .HasForeignKey("zamanlama_id")
                        .HasConstraintName("FK__RAPOR_SAB__zaman__531856C7");

                    b.Navigation("cikti_formati");

                    b.Navigation("olusturan_kullanici");

                    b.Navigation("rapor_tipi");

                    b.Navigation("zamanlama");
                });

            modelBuilder.Entity("SigortaYonetimAPI.Models.SIFRE_SIFIRLAMA", b =>
                {
                    b.HasOne("SigortaYonetimAPI.Models.KULLANICILAR", "kullanici")
                        .WithMany("SIFRE_SIFIRLAMAs")
                        .HasForeignKey("kullanici_id")
                        .IsRequired()
                        .HasConstraintName("FK__SIFRE_SIF__kulla__45F365D3");

                    b.Navigation("kullanici");
                });

            modelBuilder.Entity("SigortaYonetimAPI.Models.SISTEM_LOGLARI", b =>
                {
                    b.HasOne("SigortaYonetimAPI.Models.DURUM_TANIMLARI", "islem_tipi")
                        .WithMany("SISTEM_LOGLARIs")
                        .HasForeignKey("islem_tipi_id")
                        .HasConstraintName("FK__SISTEM_LO__islem__43D61337");

                    b.HasOne("SigortaYonetimAPI.Models.KULLANICILAR", "kullanici")
                        .WithMany("SISTEM_LOGLARIs")
                        .HasForeignKey("kullanici_id")
                        .HasConstraintName("FK__SISTEM_LO__kulla__42E1EEFE");

                    b.Navigation("islem_tipi");

                    b.Navigation("kullanici");
                });

            modelBuilder.Entity("SigortaYonetimAPI.Models.TAKSITLER", b =>
                {
                    b.HasOne("SigortaYonetimAPI.Models.DURUM_TANIMLARI", "durum")
                        .WithMany("TAKSITLERdurums")
                        .HasForeignKey("durum_id")
                        .IsRequired()
                        .HasConstraintName("FK__TAKSITLER__durum__245D67DE");

                    b.HasOne("SigortaYonetimAPI.Models.DURUM_TANIMLARI", "hatirlatma_durumu")
                        .WithMany("TAKSITLERhatirlatma_durumus")
                        .HasForeignKey("hatirlatma_durumu_id")
                        .HasConstraintName("FK__TAKSITLER__hatir__25518C17");

                    b.HasOne("SigortaYonetimAPI.Models.ODEMELER", "odeme")
                        .WithMany()
                        .HasForeignKey("odemeid");

                    b.HasOne("SigortaYonetimAPI.Models.POLISELER", "police")
                        .WithMany("TAKSITLERs")
                        .HasForeignKey("police_id")
                        .IsRequired()
                        .HasConstraintName("FK__TAKSITLER__polic__236943A5");

                    b.Navigation("durum");

                    b.Navigation("hatirlatma_durumu");

                    b.Navigation("odeme");

                    b.Navigation("police");
                });

            modelBuilder.Entity("SigortaYonetimAPI.Models.ApplicationUser", b =>
                {
                    b.Navigation("AstKullanicilar");
                });

            modelBuilder.Entity("SigortaYonetimAPI.Models.DURUM_TANIMLARI", b =>
                {
                    b.Navigation("BILDIRIMLERbildirim_tipis");

                    b.Navigation("BILDIRIMLERdurums");

                    b.Navigation("BILDIRIMLERonceliks");

                    b.Navigation("DOGRULAMA_KODLARIamacs");

                    b.Navigation("DOGRULAMA_KODLARItips");

                    b.Navigation("DOKUMANLARdosya_tipis");

                    b.Navigation("DOKUMANLARgizlilik_seviyesis");

                    b.Navigation("DOKUMANLARiliski_tipis");

                    b.Navigation("DOKUMANLARkategoris");

                    b.Navigation("HASAR_DOSYALARdurums");

                    b.Navigation("HASAR_DOSYALARolay_tipis");

                    b.Navigation("HASAR_TAKIP_NOTLARIs");

                    b.Navigation("KOMISYON_HESAPLARIs");

                    b.Navigation("KULLANICILARs");

                    b.Navigation("MUSTERILERcinsiyets");

                    b.Navigation("MUSTERILERegitim_durumus");

                    b.Navigation("MUSTERILERmedeni_durums");

                    b.Navigation("MUSTERILERtips");

                    b.Navigation("ODEMELERdurums");

                    b.Navigation("ODEMELERodeme_tipis");

                    b.Navigation("ODEMELERodeme_yontemis");

                    b.Navigation("POLICE_TEKLIFLERIs");

                    b.Navigation("POLICE_TURLERIalt_kategoris");

                    b.Navigation("POLICE_TURLERIkategoris");

                    b.Navigation("POLISELERs");

                    b.Navigation("RAPOR_SABLONLARIcikti_formatis");

                    b.Navigation("RAPOR_SABLONLARIrapor_tipis");

                    b.Navigation("RAPOR_SABLONLARIzamanlamas");

                    b.Navigation("SISTEM_LOGLARIs");

                    b.Navigation("TAKSITLERdurums");

                    b.Navigation("TAKSITLERhatirlatma_durumus");
                });

            modelBuilder.Entity("SigortaYonetimAPI.Models.HASAR_DOSYALAR", b =>
                {
                    b.Navigation("HASAR_TAKIP_NOTLARIs");
                });

            modelBuilder.Entity("SigortaYonetimAPI.Models.KULLANICILAR", b =>
                {
                    b.Navigation("BILDIRIMLERs");

                    b.Navigation("DOGRULAMA_KODLARIs");

                    b.Navigation("DOKUMANLARs");

                    b.Navigation("HASAR_DOSYALARbildiren_kullanicis");

                    b.Navigation("HASAR_DOSYALARsorumlu_ekspers");

                    b.Navigation("HASAR_TAKIP_NOTLARIs");

                    b.Navigation("KOMISYON_HESAPLARIs");

                    b.Navigation("MUSTERILERs");

                    b.Navigation("ODEMELERs");

                    b.Navigation("POLICE_TEKLIFLERIs");

                    b.Navigation("POLISELERs");

                    b.Navigation("RAPOR_SABLONLARIs");

                    b.Navigation("SIFRE_SIFIRLAMAs");

                    b.Navigation("SISTEM_LOGLARIs");
                });

            modelBuilder.Entity("SigortaYonetimAPI.Models.MUSTERILER", b =>
                {
                    b.Navigation("HASAR_DOSYALARs");

                    b.Navigation("ODEMELERs");

                    b.Navigation("POLICE_TEKLIFLERIs");

                    b.Navigation("POLISELERs");
                });

            modelBuilder.Entity("SigortaYonetimAPI.Models.POLICE_TEKLIFLERI", b =>
                {
                    b.Navigation("POLISELERs");
                });

            modelBuilder.Entity("SigortaYonetimAPI.Models.POLICE_TURLERI", b =>
                {
                    b.Navigation("POLICE_TEKLIFLERIs");

                    b.Navigation("POLISELERs");
                });

            modelBuilder.Entity("SigortaYonetimAPI.Models.POLISELER", b =>
                {
                    b.Navigation("HASAR_DOSYALARs");

                    b.Navigation("KOMISYON_HESAPLARIs");

                    b.Navigation("ODEMELERs");

                    b.Navigation("TAKSITLERs");
                });

            modelBuilder.Entity("SigortaYonetimAPI.Models.SIGORTA_SIRKETLERI", b =>
                {
                    b.Navigation("POLICE_TEKLIFLERIs");

                    b.Navigation("POLISELERs");
                });

            modelBuilder.Entity("SigortaYonetimAPI.Models.TAKSITLER", b =>
                {
                    b.Navigation("ODEMELERs");
                });
#pragma warning restore 612, 618
        }
    }
}
